### ISSUE TITLE
Create PostgreSQL database 

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#1]
In order for this story to be considered complete, the following criteria should be met,

-We have a script to create our schema in a PostgresSQL database
-The database is hosted somewhere that we can all access
-At least one other person has tested that they can connect to the database

**Comment by sawyerwatts** [comment]
Whoever picks this up, please check in with me.

**Comment by sawyerwatts** [comment]
I have ctran_data built. I will write functions to create the other three tables (duplicates, flags, flagged_rows).

**Comment by Durecka** [comment]
@sawyerwatts Could you confirm what, if anything, is left that I should complete?

**Comment by sawyerwatts** [comment]
You got the CAT to host the database, so that's done. Since creating the schema was necessary and super related to building the different tables and filling with data, I have done that. David has confirmed that this is viewable via pgadmin. So you are all set, I was going to close this one my PR is accepted.
