### ISSUE TITLE
Query Aperture from Comand Line

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#31]
In order for this story to be complete the following must be possible

-From the command line, basic queries of the database must be possible
-Must be able to query for specific row ID and its flags
-Must be able to query for a certain amount(which is inputted) of flags(i.e the last ten rows flagged with null x-coord or something like that)
-Stretch : Allow for custom queries to be run, either written in the command line in SQL or make a basic SQL query creator

**Comment by Durecka** [comment]
Already working on this from overlap with Issue #3 .

**Comment by Durecka** [comment]
I will leave function call stubs for use in future Issue(s) to handle output for these queries.

**Comment by Durecka** [comment]
I will leave the query for some quantity of flagged rows as a raw flag_id for this sprint.

Recommended future stories:
- Add a name attribute to "flags" table to eliminate magic number searches from the command line
- Create dictionary of flag ids, name, and description that gets populated in the program only when a user is interacting through the command line
- Update command line queries to use flag name instead of id

**Comment by NelsonG6** [comment]
you're finished
